server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Listado automático si no hay index.html
    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;

    # Que los .md y .xml se sirvan como texto plano (no descarga)
    types {
        text/markdown               md;
        text/plain                  log txt;
        application/xml             xml;
        application/json            json;
        text/html                   html htm;
        text/css                    css;
        application/javascript      js;
    }

    # CORS abierto (solo es localhost)
    add_header Access-Control-Allow-Origin *;

    location / {
        try_files $uri $uri/ =404;
    }
}
