<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Detalle del Boleto</title>
</head>

<body>
<div align="center" width="100%" border="2px">
    <div align="center" valign="top">
        <br> <br>
        <div width="600" border="3px">

            <div style="font-size: 48px; color:black; font-family: Arial;">
                <b>Detalles del Boleto</b>
            </div>

            <div style="font-size: 24px; color: black;">
                <br>  <b>Tu pago se realizó exitosamente</b> <br>
            </div>

            <div>
                <br> Estimado/a ${fullName}, gracias por elegir CineVision para comprar tu boleto.<br>
                <br>
                <h3>Detalles del Boleto</h3>
                <h4>${movieName}</h4>
                <br>
                <h5><b>Fecha: </b> ${movieDay} </h5>
                <h5><b>Cine: </b> ${saloonName} </h5>
                <h5><b>Función: </b> ${movieStartTime} </h5>
                <h5><b>Asientos: </b> ${chairNumbers} </h5>

            </div>
            <br>
            <div>
                <h4>De parte de la familia CineVision, ¡disfruta de la función!</h4>
            </div>
        </div>

        <br> <br>

    </div>
</div>
</body>
</html>
